import type {
  FullGarage,
  GalleryPhoto,
  PublicUserSummary,
  TimelineComment,
  VehicleDetail,
} from "@/types/garage";

const IMG = {
  banner:
    "https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?auto=format&fit=crop&w=2400&q=80",
  avatar:
    "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80",
  mustang:
    "https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=1600&q=80",
  camaro:
    "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=1600&q=80",
  corvette:
    "https://images.unsplash.com/photo-1583121274602-3e2820c69888?auto=format&fit=crop&w=1600&q=80",
  garage:
    "https://images.unsplash.com/photo-1487754180451-c456f719a1fc?auto=format&fit=crop&w=1600&q=80",
  dyno: "https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?auto=format&fit=crop&w=1600&q=80",
  rolling:
    "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1600&q=80",
  engine:
    "https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?auto=format&fit=crop&w=1600&q=80",
  before:
    "https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?auto=format&fit=crop&w=1600&q=80",
};

const followers: PublicUserSummary[] = [
  {
    id: "u2",
    username: "midnightcamaro",
    displayName: "Alex Rivera",
    avatarUrl:
      "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=200&q=80",
    garageRank: "Tuner",
    location: "Austin, TX",
  },
  {
    id: "u3",
    username: "zcar_diary",
    displayName: "Jordan Lee",
    avatarUrl:
      "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&w=200&q=80",
    garageRank: "Builder",
    location: "San Diego, CA",
  },
  {
    id: "u4",
    username: "truckbench",
    displayName: "Morgan Blake",
    avatarUrl:
      "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80",
    garageRank: "Fabricator",
    location: "Denver, CO",
  },
];

const following: PublicUserSummary[] = [
  followers[0],
  followers[2],
  {
    id: "u5",
    username: "corvette_lab",
    displayName: "Sam Ortiz",
    avatarUrl:
      "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=200&q=80",
    garageRank: "Master Mechanic",
    location: "Miami, FL",
  },
];

const gallery: GalleryPhoto[] = [
  {
    id: "g1",
    ownerId: "u1",
    vehicleId: "v1",
    url: IMG.mustang,
    caption: "Evening light on the S550",
    album: "Rolling Shots",
    createdAt: "2025-11-02",
  },
  {
    id: "g2",
    ownerId: "u1",
    vehicleId: "v1",
    url: IMG.engine,
    caption: "Coyote bay after intake swap",
    album: "Build Photos",
    createdAt: "2025-09-18",
  },
  {
    id: "g3",
    ownerId: "u1",
    vehicleId: "v2",
    url: IMG.camaro,
    caption: "Before: stock stance",
    album: "Before / After",
    createdAt: "2024-06-12",
  },
  {
    id: "g4",
    ownerId: "u1",
    vehicleId: "v2",
    url: IMG.before,
    caption: "After: coilovers and square setup",
    album: "Before / After",
    createdAt: "2025-03-01",
  },
  {
    id: "g5",
    ownerId: "u1",
    url: IMG.garage,
    caption: "Sunday morning garage reset",
    album: "Garage Photos",
    createdAt: "2025-12-20",
  },
  {
    id: "g6",
    ownerId: "u1",
    vehicleId: "v1",
    url: IMG.dyno,
    caption: "Latest pull — 612 whp",
    album: "Dyno Sheets",
    createdAt: "2026-01-14",
  },
  {
    id: "g7",
    ownerId: "u1",
    vehicleId: "v3",
    url: IMG.corvette,
    caption: "C7 detail day",
    album: "Rolling Shots",
    createdAt: "2025-08-08",
  },
  {
    id: "g8",
    ownerId: "u1",
    vehicleId: "v1",
    url: IMG.rolling,
    caption: "Highway pull, third gear",
    album: "Rolling Shots",
    createdAt: "2026-02-02",
  },
];

export const DEMO_GARAGE: FullGarage = {
  profile: {
    id: "u1",
    username: "tunedgarage",
    displayName: "Chris Harper",
    avatarUrl: IMG.avatar,
    bannerUrl: IMG.banner,
    accentColor: "#C8B49A",
    bio: "Home mechanic building honest horsepower one weekend at a time. Coyote swaps, street manners, and clean documentation.",
    location: "Charlotte, NC",
    memberSince: "2022-03-14",
    garageRank: "Fabricator",
    favoriteManufacturer: "Ford",
    favoriteEngine: "5.0 Coyote",
    favoriteBuildStyle: "Street / Track",
    favoriteQuote: "Measure twice. Torque once. Drive forever.",
    socialLinks: {
      youtube: "https://youtube.com/@tunedgarage",
      instagram: "https://instagram.com/tunedgarage",
      tiktok: "https://tiktok.com/@tunedgarage",
      website: "https://tunedandthreaded.com",
    },
    badges: [
      "first_build",
      "weekend_wrench",
      "engine_builder",
      "forced_induction",
      "photographer",
      "helpful_member",
    ],
    stats: {
      followers: 1284,
      following: 186,
      vehicles: 3,
      builds: 5,
      journalEntries: 47,
      completedProjects: 2,
      combinedHorsepower: 1487,
      reputationScore: 92,
      yearsBuilding: 8,
      estimatedInvested: 68400,
    },
    isFollowing: false,
  },
  vehicles: [
    {
      id: "v1",
      ownerId: "u1",
      photoUrl: IMG.mustang,
      year: 2018,
      make: "Ford",
      model: "Mustang",
      trim: "GT Premium",
      engine: "5.0L Coyote V8",
      transmission: "6MT",
      mileage: 41200,
      currentHorsepower: 612,
      targetHorsepower: 700,
      currentStage: "Tuning",
      upcomingStage: "Detailing",
      progressPercent: 78,
      estimatedCompletion: "2026-09-01",
      notes:
        "Primary daily-capable street build. Focused on reliability above 600 whp.",
      futureGoals: [
        "Final dyno tune at 700 whp target",
        "Track day cooling package",
        "Interior refresh with Alcantara",
      ],
    },
    {
      id: "v2",
      ownerId: "u1",
      photoUrl: IMG.camaro,
      year: 2016,
      make: "Chevrolet",
      model: "Camaro",
      trim: "SS 1LE",
      engine: "6.2L LT1 V8",
      transmission: "8AT",
      mileage: 53800,
      currentHorsepower: 455,
      targetHorsepower: 550,
      currentStage: "Assembly",
      upcomingStage: "Tuning",
      progressPercent: 54,
      estimatedCompletion: "2026-12-15",
      notes: "Weekend canyon car. Suspension-first philosophy.",
      futureGoals: ["Cam/headers package", "Brake ducting", "Lightweight wheels"],
    },
    {
      id: "v3",
      ownerId: "u1",
      photoUrl: IMG.corvette,
      year: 2019,
      make: "Chevrolet",
      model: "Corvette",
      trim: "Stingray Z51",
      engine: "6.2L LT2 V8",
      transmission: "8AT",
      mileage: 22100,
      currentHorsepower: 420,
      targetHorsepower: 420,
      currentStage: "Complete",
      progressPercent: 100,
      estimatedCompletion: "2025-05-01",
      notes: "Preserve factory character. Light cosmetic and maintenance focus.",
      futureGoals: ["Annual track prep", "Ceramic coat refresh"],
    },
  ],
  gallery,
  followers,
  following,
};

export const DEMO_VEHICLE_DETAILS: Record<string, VehicleDetail> = {
  v1: {
    vehicle: DEMO_GARAGE.vehicles[0],
    photos: gallery.filter((p) => p.vehicleId === "v1"),
    installedParts: [
      {
        id: "p1",
        vehicleId: "v1",
        name: "Whipple Gen 5 3.0L Supercharger",
        brand: "Whipple",
        category: "Forced Induction",
        installed: true,
        cost: 8200,
        installedAt: "2025-04-12",
      },
      {
        id: "p2",
        vehicleId: "v1",
        name: "Long Tube Headers",
        brand: "American Racing",
        category: "Exhaust",
        installed: true,
        cost: 1450,
        installedAt: "2024-11-03",
      },
      {
        id: "p3",
        vehicleId: "v1",
        name: "Billet Oil Separator",
        brand: "J&L",
        category: "Engine",
        installed: true,
        cost: 340,
        installedAt: "2024-08-20",
      },
    ],
    futureParts: [
      {
        id: "p4",
        vehicleId: "v1",
        name: "Track Radiator Package",
        brand: "CSF",
        category: "Cooling",
        installed: false,
        cost: 980,
      },
      {
        id: "p5",
        vehicleId: "v1",
        name: "Alcantara Interior Kit",
        brand: "Recaro",
        category: "Interior",
        installed: false,
        cost: 2100,
      },
    ],
    timeline: [
      {
        id: "t1",
        vehicleId: "v1",
        title: "Supercharger install weekend",
        date: "2025-04-12",
        description:
          "Full Whipple install with charge pipes, injectors, and pulley. First fire-up was clean — idle settled after heat cycle.",
        photos: [IMG.engine, IMG.mustang],
        partsInstalled: ["Whipple Gen 5 3.0L Supercharger", "High-flow injectors"],
        cost: 9200,
        timeSpentHours: 18,
        likes: 214,
        comments: 32,
      },
      {
        id: "t2",
        vehicleId: "v1",
        title: "Dyno baseline after break-in",
        date: "2026-01-14",
        description:
          "Third pull settled at 612 whp / 548 wtq on 93. AFR and timing look healthy. Next session aims for the 700 goal.",
        photos: [IMG.dyno],
        videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        partsInstalled: [],
        cost: 250,
        timeSpentHours: 4,
        likes: 389,
        comments: 51,
      },
      {
        id: "t3",
        vehicleId: "v1",
        title: "Header and midpipe refresh",
        date: "2024-11-03",
        description:
          "Long tubes and high-flow cats. Sound is deeper without drone on the highway.",
        photos: [IMG.garage],
        partsInstalled: ["Long Tube Headers"],
        cost: 1680,
        timeSpentHours: 9,
        likes: 96,
        comments: 14,
      },
    ],
    maintenance: [
      {
        id: "m1",
        vehicleId: "v1",
        title: "Oil + filter",
        date: "2026-02-01",
        mileage: 41200,
        notes: "Motul 5W-50 after dyno session.",
        cost: 120,
      },
      {
        id: "m2",
        vehicleId: "v1",
        title: "Brake fluid flush",
        date: "2025-10-18",
        mileage: 39850,
        notes: "DOT 4 Motul RBF 600.",
        cost: 85,
      },
    ],
    dynoResults: [
      {
        id: "d1",
        vehicleId: "v1",
        date: "2026-01-14",
        horsepower: 612,
        torque: 548,
        boostPsi: 12,
        notes: "93 octane, 70°F ambient",
        sheetUrl: IMG.dyno,
      },
      {
        id: "d2",
        vehicleId: "v1",
        date: "2025-05-02",
        horsepower: 574,
        torque: 521,
        boostPsi: 11,
        notes: "Post-install conservative tune",
        sheetUrl: IMG.dyno,
      },
    ],
    quarterMileTimes: [
      {
        id: "q1",
        vehicleId: "v1",
        date: "2025-09-21",
        et: 11.42,
        trapSpeed: 124.8,
        reactionTime: 0.312,
        notes: "Street radial, 70° evening",
      },
    ],
  },
  v2: {
    vehicle: DEMO_GARAGE.vehicles[1],
    photos: gallery.filter((p) => p.vehicleId === "v2"),
    installedParts: [
      {
        id: "p6",
        vehicleId: "v2",
        name: "Coilover Kit",
        brand: "KW V3",
        category: "Suspension",
        installed: true,
        cost: 2800,
        installedAt: "2025-02-14",
      },
    ],
    futureParts: [
      {
        id: "p7",
        vehicleId: "v2",
        name: "Cam & Headers Package",
        brand: "Texas Speed",
        category: "Engine",
        installed: false,
        cost: 3600,
      },
    ],
    timeline: [
      {
        id: "t4",
        vehicleId: "v2",
        title: "Suspension geometry dial-in",
        date: "2025-03-01",
        description:
          "Coilovers set, alignment locked for canyon work. Front grip improved immediately.",
        photos: [IMG.camaro, IMG.before],
        partsInstalled: ["Coilover Kit"],
        cost: 3100,
        timeSpentHours: 7,
        likes: 142,
        comments: 19,
      },
    ],
    maintenance: [
      {
        id: "m3",
        vehicleId: "v2",
        title: "Differential fluid",
        date: "2025-07-10",
        mileage: 52100,
        notes: "OEM fluid, no metal.",
        cost: 95,
      },
    ],
    dynoResults: [
      {
        id: "d3",
        vehicleId: "v2",
        date: "2024-12-01",
        horsepower: 455,
        torque: 455,
        notes: "Stock baseline",
      },
    ],
    quarterMileTimes: [],
  },
  v3: {
    vehicle: DEMO_GARAGE.vehicles[2],
    photos: gallery.filter((p) => p.vehicleId === "v3"),
    installedParts: [
      {
        id: "p8",
        vehicleId: "v3",
        name: "Ceramic Coating",
        brand: "Gtechniq",
        category: "Detail",
        installed: true,
        cost: 1200,
        installedAt: "2025-04-20",
      },
    ],
    futureParts: [],
    timeline: [
      {
        id: "t5",
        vehicleId: "v3",
        title: "Preservation complete",
        date: "2025-05-01",
        description:
          "Detail package finished. Build marked complete — maintenance mode only.",
        photos: [IMG.corvette],
        partsInstalled: ["Ceramic Coating"],
        cost: 1200,
        timeSpentHours: 6,
        likes: 88,
        comments: 9,
      },
    ],
    maintenance: [
      {
        id: "m4",
        vehicleId: "v3",
        title: "Annual inspection",
        date: "2026-01-05",
        mileage: 22100,
        notes: "All systems nominal.",
        cost: 0,
      },
    ],
    dynoResults: [],
    quarterMileTimes: [],
  },
};

export const DEMO_COMMENTS: Record<string, TimelineComment[]> = {
  t1: [
    {
      id: "c1",
      updateId: "t1",
      authorUsername: "midnightcamaro",
      authorDisplayName: "Alex Rivera",
      authorAvatarUrl: followers[0].avatarUrl,
      body: "Clean install. That bay looks factory-plus.",
      createdAt: "2025-04-13T14:20:00Z",
    },
    {
      id: "c2",
      updateId: "t1",
      authorUsername: "zcar_diary",
      authorDisplayName: "Jordan Lee",
      authorAvatarUrl: followers[1].avatarUrl,
      body: "What pulley are you running for street manners?",
      createdAt: "2025-04-13T18:05:00Z",
    },
  ],
  t2: [
    {
      id: "c3",
      updateId: "t2",
      authorUsername: "truckbench",
      authorDisplayName: "Morgan Blake",
      authorAvatarUrl: followers[2].avatarUrl,
      body: "612 on 93 is serious. Excited for the 700 pull.",
      createdAt: "2026-01-14T21:10:00Z",
    },
  ],
};

